### ISSUE TITLE
There are lint errors in the code

### ISSUE THREAD

**Issue by master-of-none** [master-of-none/image-text-translation#22]
./app.py:14:1: E302 expected 2 blank lines, found 1
./app.py:17:1: E302 expected 2 blank lines, found 1
./app.py:22:1: W293 blank line contains whitespace
./app.py:26:1: W293 blank line contains whitespace
./app.py:35:1: E302 expected 2 blank lines, found 1
./app.py:42:1: E305 expected 2 blank lines after class or function definition, found 1
3     E302 expected 2 blank lines, found 1
1     E305 expected 2 blank lines after class or function definition, found 1
2     W293 blank line contains whitespace

Check for these errors and fix these.

**Comment by suhasdwarakanath** [comment]
Issue has been resolved in pull request #28
